### ISSUE TITLE
Configure Parse Server

### ISSUE THREAD

**Issue by bryanuribe** [bryanuribe/InstagramClone#1]
- Deploy to Heroku
- Test deployment
- Setup Local Parse Dashboard
- Add Parse Client to Project

**Comment by codepathreview** [comment]
It looks like your video walkthrough doesn't seem to show some of the required stories as follows:

1. User can sign up to create a new account using Parse authentication
2. User can view the last 20 posts submitted to "Instagram"
3. User can pull to refresh the last 20 posts submitted to "Instagram"
4. User can tap a post to view post details, including timestamp and caption.

Also, one of the stretch features you listed wherein the user can capture photo in photo gallery view when switching between different tabs doesn't seem to show as well.


Can you update this and resubmit? 
/cc @codepathreview

**Comment by bryanuribe** [comment]
@codepathreview Sorry, I forgot to show those required features in the walkthrough videos. I have just resubmitted and added three walkthrough videos. My first walkthrough video includes signing up as a new user, taking a picture and posting it to parstagram, viewing a details page of a post, and lastly viewing the profile fragment for a user. My second walkthrough video includes logging in from an existing user and refreshing the page to get new instagram posts. I manually edited through parse dashboard to get this functionality. My third walkthrough video shows persistence.

**Comment by codepathreview** [comment]
Nice work, Bryan. We put together a detailed Project 4 Feedback Guide here: (http://courses.codepath.org/snippets/android_university_fast_track/feedback_guides/project_4_feedback) which covers the most common issues with this project. Read through the feedback guide point-by-point to determine how you could improve your submission.

We hope you enjoyed the course and learned a lot in the process and look forward to see what you build for your final internship project!
 
/cc @codepathreview
